[package]
name = "ableton-git"
version = "0.1.0"
authors = ["Clinton Burgos <clintburgos@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "ableton-git"
path = "src/main.rs"
